
import sys
import pprint
import os
import jinja2
import webbrowser


current_dir = os.path.dirname(os.path.abspath(__file__))
templates_path = os.path.join(current_dir, 'templates')

env = jinja2.Environment(loader=jinja2.FileSystemLoader(templates_path))
template = env.get_template('report.html')

datasets_test = [{'estado': 'error',
  'images': [{'description': 'Realibiliy Plot',
              'path': 'images/sofia_test_1_rel.eps',
              'software-id': 'sofia',
              'type': 'rel'},
             {'description': 'Skellman Plot',
              'path': 'images/sofia_test_1_skellam.eps',
              'software-id': 'sofia',
              'type': 'skellman'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_1_1_mom0.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_1_1_mom1.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_1_1_mom2.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_1_1_spec.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_1_1_pv.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_1_1_pv_min.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_1_2_mom0.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_1_2_mom1.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_1_2_mom2.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_1_2_spec.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_1_2_pv.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_1_2_pv_min.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_1_3_mom0.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_1_3_mom1.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_1_3_mom2.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_1_3_spec.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_1_3_pv.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_1_3_pv_min.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_1_4_mom0.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_1_4_mom1.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_1_4_mom2.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_1_4_spec.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_1_4_pv.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_1_4_pv_min.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv_min'}],
  'images_grouped': {'qa': [],
                     'sip': {1: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_1_1_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_1_1_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_1_1_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_1_1_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_1_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_1_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv_min'}],
                             2: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_1_2_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_1_2_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_1_2_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_1_2_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_2_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_2_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv_min'}],
                             3: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_1_3_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_1_3_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_1_3_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_1_3_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_3_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_3_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv_min'}],
                             4: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_1_4_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_1_4_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_1_4_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_1_4_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_4_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_4_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv_min'}]},
                     'sofia': [{'description': 'Realibiliy Plot',
                                'path': 'images/sofia_test_1_rel.eps',
                                'software-id': 'sofia',
                                'type': 'rel'},
                               {'description': 'Skellman Plot',
                                'path': 'images/sofia_test_1_skellam.eps',
                                'software-id': 'sofia',
                                'type': 'skellman'}]},
  'input_data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_1.fits',
  'softwares': [{'error': "Command '['sofia', "
                          "'/home/usuario/ADP-ALMA-Pipeline/sofia_abs_default_tmp_PID14629.par']' "
                          'returned non-zero exit status 8.',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_1_logfile.log',
                 'modo': 'absorption',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_1.fits',
                                       'input.invert': 'true',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'error'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_1_logfile.log',
                 'modo': 'emission',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_1.fits',
                                       'input.invert': 'false',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_1_sip.log',
                 'modo': 'absorption',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_1_sip.log',
                 'modo': 'emission',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'}]},
 {'estado': 'error',
  'images': [{'description': 'Realibiliy Plot',
              'path': 'images/sofia_test_rel.eps',
              'software-id': 'sofia',
              'type': 'rel'},
             {'description': 'Skellman Plot',
              'path': 'images/sofia_test_skellam.eps',
              'software-id': 'sofia',
              'type': 'skellman'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_1_mom0.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_1_mom1.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_1_mom2.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_1_spec.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_1_pv.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_1_pv_min.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_2_mom0.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_2_mom1.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_2_mom2.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_2_spec.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_2_pv.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_2_pv_min.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_3_mom0.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_3_mom1.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_3_mom2.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_3_spec.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_3_pv.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_3_pv_min.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_4_mom0.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_4_mom1.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_4_mom2.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_4_spec.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_4_pv.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_4_pv_min.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv_min'}],
  'images_grouped': {'qa': [],
                     'sip': {1: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_1_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_1_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_1_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_1_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_1_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv_min'}],
                             2: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_2_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_2_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_2_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_2_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv_min'}],
                             3: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_3_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_3_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_3_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_3_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv_min'}],
                             4: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_4_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_4_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_4_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_4_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_4_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_4_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv_min'}]},
                     'sofia': [{'description': 'Realibiliy Plot',
                                'path': 'images/sofia_test_rel.eps',
                                'software-id': 'sofia',
                                'type': 'rel'},
                               {'description': 'Skellman Plot',
                                'path': 'images/sofia_test_skellam.eps',
                                'software-id': 'sofia',
                                'type': 'skellman'}]},
  'input_data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test.fits',
  'softwares': [{'error': "Command '['sofia', "
                          "'/home/usuario/ADP-ALMA-Pipeline/sofia_abs_default_tmp_PID14628.par']' "
                          'returned non-zero exit status 8.',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_logfile.log',
                 'modo': 'absorption',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test.fits',
                                       'input.invert': 'true',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'error'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_logfile.log',
                 'modo': 'emission',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test.fits',
                                       'input.invert': 'false',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_sip.log',
                 'modo': 'absorption',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_sip.log',
                 'modo': 'emission',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'}]},
 {'estado': 'error',
  'images': [{'description': 'Realibiliy Plot',
              'path': 'images/sofia_test_2_rel.eps',
              'software-id': 'sofia',
              'type': 'rel'},
             {'description': 'Skellman Plot',
              'path': 'images/sofia_test_2_skellam.eps',
              'software-id': 'sofia',
              'type': 'skellman'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_2_1_mom0.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_2_1_mom1.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_2_1_mom2.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_2_1_spec.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_2_1_pv.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_2_1_pv_min.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_2_2_mom0.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_2_2_mom1.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_2_2_mom2.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_2_2_spec.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_2_2_pv.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_2_2_pv_min.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_2_3_mom0.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_2_3_mom1.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_2_3_mom2.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_2_3_spec.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_2_3_pv.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_2_3_pv_min.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_2_4_mom0.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_2_4_mom1.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_2_4_mom2.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_2_4_spec.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_2_4_pv.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_2_4_pv_min.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv_min'}],
  'images_grouped': {'qa': [],
                     'sip': {1: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_2_1_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_2_1_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_2_1_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_2_1_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_1_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_1_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv_min'}],
                             2: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_2_2_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_2_2_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_2_2_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_2_2_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_2_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_2_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv_min'}],
                             3: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_2_3_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_2_3_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_2_3_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_2_3_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_3_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_3_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv_min'}],
                             4: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_2_4_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_2_4_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_2_4_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_2_4_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_4_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_2_4_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv_min'}]},
                     'sofia': [{'description': 'Realibiliy Plot',
                                'path': 'images/sofia_test_2_rel.eps',
                                'software-id': 'sofia',
                                'type': 'rel'},
                               {'description': 'Skellman Plot',
                                'path': 'images/sofia_test_2_skellam.eps',
                                'software-id': 'sofia',
                                'type': 'skellman'}]},
  'input_data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_2.fits',
  'softwares': [{'error': "Command '['sofia', "
                          "'/home/usuario/ADP-ALMA-Pipeline/sofia_abs_default_tmp_PID14630.par']' "
                          'returned non-zero exit status 8.',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_2_logfile.log',
                 'modo': 'absorption',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_2.fits',
                                       'input.invert': 'true',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'error'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_2_logfile.log',
                 'modo': 'emission',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_2.fits',
                                       'input.invert': 'false',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_2_sip.log',
                 'modo': 'absorption',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_2_sip.log',
                 'modo': 'emission',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'}]},
 {'estado': 'error',
  'images': [{'description': 'Realibiliy Plot',
              'path': 'images/sofia_test_3_rel.eps',
              'software-id': 'sofia',
              'type': 'rel'},
             {'description': 'Skellman Plot',
              'path': 'images/sofia_test_3_skellam.eps',
              'software-id': 'sofia',
              'type': 'skellman'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_3_1_mom0.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_3_1_mom1.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_3_1_mom2.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_3_1_spec.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_3_1_pv.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_3_1_pv_min.png',
              'software-id': 'sip',
              'source_id': 1,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_3_2_mom0.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_3_2_mom1.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_3_2_mom2.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_3_2_spec.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_3_2_pv.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_3_2_pv_min.png',
              'software-id': 'sip',
              'source_id': 2,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_3_3_mom0.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_3_3_mom1.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_3_3_mom2.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_3_3_spec.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_3_3_pv.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_3_3_pv_min.png',
              'software-id': 'sip',
              'source_id': 3,
              'type': 'pv_min'},
             {'description': 'Momment 0 image',
              'path': 'images/sofia_test_3_4_mom0.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom0'},
             {'description': 'Momment 1 image',
              'path': 'images/sofia_test_3_4_mom1.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom1'},
             {'description': 'Momment 2 image',
              'path': 'images/sofia_test_3_4_mom2.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'mom2'},
             {'description': 'Spectrum plot',
              'path': 'images/sofia_test_3_4_spec.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'spec'},
             {'description': 'Position-Velociy (major axis) plot',
              'path': 'images/sofia_test_3_4_pv.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv'},
             {'description': 'Position-Velociy (minoe axis) plot',
              'path': 'images/sofia_test_3_4_pv_min.png',
              'software-id': 'sip',
              'source_id': 4,
              'type': 'pv_min'}],
  'images_grouped': {'qa': [],
                     'sip': {1: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_3_1_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_3_1_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_3_1_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_3_1_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_1_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_1_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 1,
                                  'type': 'pv_min'}],
                             2: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_3_2_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_3_2_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_3_2_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_3_2_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_2_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_2_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 2,
                                  'type': 'pv_min'}],
                             3: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_3_3_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_3_3_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_3_3_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_3_3_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_3_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_3_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 3,
                                  'type': 'pv_min'}],
                             4: [{'description': 'Momment 0 image',
                                  'path': 'images/sofia_test_3_4_mom0.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom0'},
                                 {'description': 'Momment 1 image',
                                  'path': 'images/sofia_test_3_4_mom1.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom1'},
                                 {'description': 'Momment 2 image',
                                  'path': 'images/sofia_test_3_4_mom2.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'mom2'},
                                 {'description': 'Spectrum plot',
                                  'path': 'images/sofia_test_3_4_spec.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'spec'},
                                 {'description': 'Position-Velociy (major '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_4_pv.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv'},
                                 {'description': 'Position-Velociy (minoe '
                                                 'axis) plot',
                                  'path': 'images/sofia_test_3_4_pv_min.png',
                                  'software-id': 'sip',
                                  'source_id': 4,
                                  'type': 'pv_min'}]},
                     'sofia': [{'description': 'Realibiliy Plot',
                                'path': 'images/sofia_test_3_rel.eps',
                                'software-id': 'sofia',
                                'type': 'rel'},
                               {'description': 'Skellman Plot',
                                'path': 'images/sofia_test_3_skellam.eps',
                                'software-id': 'sofia',
                                'type': 'skellman'}]},
  'input_data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_3.fits',
  'softwares': [{'error': "Command '['sofia', "
                          "'/home/usuario/ADP-ALMA-Pipeline/sofia_abs_default_tmp_PID14631.par']' "
                          'returned non-zero exit status 8.',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_3_logfile.log',
                 'modo': 'absorption',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_3.fits',
                                       'input.invert': 'true',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'error'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_3_logfile.log',
                 'modo': 'emission',
                 'nombre': 'SoFiA-2',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {'input.data': '/home/usuario/0Test_ADP_ALMAPipeline/test_directories/sofia_test_3.fits',
                                       'input.invert': 'false',
                                       'output.directory': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission',
                                       'pipeline.threads': '3'},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_absorption/sofia_test_3_sip.log',
                 'modo': 'absorption',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'},
                {'error': '',
                 'log_path': '/home/usuario/ADP-ALMA-Pipeline/adpalmap_outputs_emission/sofia_test_3_sip.log',
                 'modo': 'emission',
                 'nombre': 'SIP',
                 'numero_de_warning': 2,
                 'sofia_par_changes': {},
                 'sofia_parfile': '',
                 'sw_estado': 'ok'}]}]


adp_log = """2025-07-02 11:04:36,213 | INFO | [PID:8051] adpalmap: - ADPALMAP start point
2025-07-02 11:04:36,690 | INFO | [PID:8051] adpalmap: - 'enable_tap_service' set to False. Skipping data download
2025-07-02 11:04:36,691 | INFO | [PID:8051] adpalmap: - The worker number has been set to 1

=== Subprocess PID: 8064 start ===
2025-07-02 11:04:36,958 | INFO | [PID:8064] sopar: - The file in '/home/usuario/ADP-ALMA-Pipeline/adplib/sofia/sofia_emi_default.par' have been loaded successfully
2025-07-02 11:04:36,959 | INFO | [PID:8064] sopar: - Reading parameters. Mode: emission.
2025-07-02 11:04:36,960 | INFO | [PID:8064] sopar: - Parameters ready. Mode: emission.
2025-07-02 11:04:36,960 | INFO | [PID:8064] sopar: - Creating temporary SoFiA parameter file based on the parameter file /home/usuario/ADP-ALMA-Pipeline/sofia_emi_default_tmp_PID8064.par.
2025-07-02 11:04:36,961 | INFO | [PID:8064] sopar: - Parameters set for the run: 
[8064]pipeline.verbose=false
[8064]pipeline.pedantic=true
[8064]pipeline.threads=12
[8064]input.data=/home/usuario/ADP-ALMA-Pipeline/adplib/sofia/sofia_test_datacube.fits
[8064]input.primaryBeam= 
[8064]input.region=
[8064]input.gain=
"""


html = template.render(datasets=datasets_test, adp_log=adp_log)

output_file = os.path.join(current_dir, 'report_test.html')
with open(output_file, 'w') as f:
    f.write(html)

#webbrowser.open('file://' + output_file)

