#This is and example of the configuration file. 

###############
#   GENERAL   #
###############

quality_assesment: True
html_report: True
verbose: False
num_cores: 12

################
#    LOGGER    #
################

clear_logs: True
log_file: log_dir/adpalmap.log

##################
#   INPUT DATA   #
##################

input_data_set: /home/usuario/ADP-ALMA-Pipeline/adplib/sofia/sofia_test_datacube.fits
    #1: 
    #2:  
    #3: 
    #4: 

input_file: 

#####################
#    TAP SERVICE    #
#####################

enable_tap_service: False
download_par_file: ~/ADP-ALMA-Pipeline/adplib/tap/download_par.yaml

#################
#     SOFIA     #
#################

enable_sofia : True
run_mode: 'emission' #'both', 'absorption'
abs_flag_cube: True
auto_setup: False
sofia_abs_file : ~/ADP-ALMA-Pipeline/adplib/sofia/sofia_abs_default.par
sofia_emi_file :  ~/ADP-ALMA-Pipeline/adplib/sofia/sofia_emi_default.par

#################
#      SIP      #
#################

enable_sip : True
sip_par_file : ~/ADP-ALMA-Pipeline/adplib/sip/sip_args.yaml



