#This is and example of the configuration file. 

###############
#   GENERAL   #
###############

quality_assesment: True
capture_outputs: False
num_cores: 18

################
#    LOGGER    #
################

clear_logs: False
log_file: log_dir/adpalmap.log

##################
#   INPUT DATA   #
##################

#input_data: /home/usuario/ALMA_ADPPipeline/test_directories/data.txt 
input_data_set:  
    1: /home/usuario/ALMA_ADPPipeline/adp-alma-pipeline/adplib/sofia/sofia_test_datacube.fits
    2: /home/usuario/ALMA_ADPPipeline/adp-alma-pipeline/adplib/sofia/sofia_test_datacube.fits


#####################
#    TAP SERVICE    #
#####################

enable_tap_service: False
download_par_file: 

#################
#     SOFIA     #
#################

enable_sofia : True
run_mode: 'both' #'both', 'absorption'
abs_flag_cube: True
auto_setup: False
sofia_abs_file :
sofia_emi_file : 

#################
#      SIP      #
#################

enable_sip : True
sip_par_file : 



