#This is and example of the configuration file. 

###############
#   GENERAL   #
###############

quality_assesment: True
capture_outputs: False
num_cores: 12

################
#    LOGGER    #
################

clear_logs: True
log_file: log_dir/adpalmap.log

##################
#   INPUT DATA   #
##################

input_data_set: #/home/usuario/ALMA_ADPPipeline/test_directories/test253_spw3.fits
    #1: /home/usuario/ALMA_ADPPipeline/test_directories/KH2016_test.fits
    #2: /home/usuario/ALMA_ADPPipeline/test_directories/KH2016_test_1.fits  
    #3: /home/usuario/ALMA_ADPPipeline/test_directories/KH2016_test_2.fits
    #4: /home/usuario/ALMA_ADPPipeline/test_directories/KH2016_test_3.fits

input_file: #/home/usuario/ALMA_ADPPipeline/test_directories/data.txt

#####################
#    TAP SERVICE    #
#####################

enable_tap_service: True
download_par_file: 

#################
#     SOFIA     #
#################

enable_sofia : False
run_mode: 'emission' #'both', 'absorption'
abs_flag_cube: True
auto_setup: False
sofia_abs_file : /home/usuario/ALMA_ADPPipeline/adp-alma-pipeline/adplib/sofia/sofia_abs_default.par
sofia_emi_file :  /home/usuario/ALMA_ADPPipeline/adp-alma-pipeline/adplib/sofia/sofia_emi_default.par

#################
#      SIP      #
#################

enable_sip : True
sip_par_file : 



